#!/bin/bash
set -e

# Upeelechien est volontairement installé sans télécharger
# Ollama ou les modèles pendant l'installation du paquet.
#
# L'installation de ces composants est effectuée au premier
# lancement de Upeelechien.

exit 0
